scanner:
  diff_only: False
  linter: flake8

flake8:
  max-line-length: 95
  exclude:
    - misc
    - test
  ignore:
    - W503  # line break before binary operator
    - E226  # missing whitespace around arithmetic operator
